apiVersion: apps/v1
kind: Deployment
metadata:
  name: githubactions-deployment
  labels:
    app: githubaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: githubaction
  template:
    metadata:
      labels:
        app: githubaction
    spec:
      containers:
      - name: githubaction
        image: 788866596473.dkr.ecr.us-east-1.amazonaws.com/githubactions:latest
        ports:
        - containerPort: 80
