name: Docker Image CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Deploy:
   
    runs-on: ubuntu-latest
    environment: Deploy
    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TF_USER_AWS_KEY }}
        aws-secret-access-key: ${{ secrets.TF_USER_AWS_SECRET }}
        aws-region: us-east-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: pull image from Amazon ECR
      env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: githubactions
          IMAGE_TAG: githubactions_image
                
    - uses: appleboy/ssh-action@master    
      name: Docker pull & run from github
          uses
      with:
          host: ec2-44-202-140-5.compute-1.amazonaws.com
          username: ec2-user
          key: ${{ secrets.ACTIONS_PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            docker login
            docker pull $IMAGE_TAG
#            docker run  $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
