name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3   
    
    - name: install kubectl
      uses: azure/setup-kubectl@v3
      id: install
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TF_USER_AWS_KEY }}
        aws-secret-access-key: ${{ secrets.TF_USER_AWS_SECRET }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Build, tag and push image to ECR
      env: 
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ecs
        IMAGE_TAG: eks_githubactions
      run : |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push  $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
    - name: update kube config
      run: aws eks update-kubeconfig --name test-ghactions --region us-east-1
      
      
    - name: Deploy to EKS
      run: kubectl apply -f githubactions.yml
      
