name: snyk security scan

on:
  workflow_dispatch:
  pull_request:

jobs:
  Security:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@v2
      - name: Run Snyk to check for vulnerabilities  #package.json and JavaScript/Node.js files
        run: |
           npx snyk test --all-projects app.js src --severity-threshold=high
           #npx snyk container test --severity-threshold=high, critical
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
