name: Example workflow for Snyk Generic Code Scan
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Use the latest version of the checkout action
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/generic@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
